### ISSUE TITLE
Issue with CWMP XSD

### ISSUE THREAD

**Issue by bpbp-boop** [mibes404/zeep#1]
Hi, I am fairly new to XSD and trying to generate code from the following:
https://cwmp-data-models.broadband-forum.org/cwmp-1-2.xsd

```
~/zeep$ ./target/release/zeep -p resources/cwmp -i cwmp-1-2.xsd

Failed to process cwmp-1-2.xsd: writer error: No such file or directory (os error 2)
```
I think I have the other XSDs needed
```
~/zeep$ ls resources/cwmp/
cwmp-1-0.xsd  cwmp-1-1.xsd  cwmp-1-2.xsd  cwmp-1-3.xsd  cwmp-1-4.xsd
```

The hello example works fine to stdout. Am I missing some other detail maybe?
Thanks!

**Comment by mibes404** [comment]
Hi, the current version of Zeep can not handle networked import statements. These 4 lines are breaking the process:

```xml
  <xs:import namespace="http://schemas.xmlsoap.org/soap/envelope/"
             schemaLocation="http://schemas.xmlsoap.org/soap/envelope/"/>
  <xs:import namespace="http://schemas.xmlsoap.org/soap/encoding/"
             schemaLocation="http://schemas.xmlsoap.org/soap/encoding/"/>
```

However, after removing these lines, the conversion process seems to complete succesfully. (At least it is producing valid Rust code).

Hope this helps.

**Comment by bpbp-boop** [comment]
I see, thank you
