### ISSUE TITLE
Feature request: extract a `zeep-core` crate

### ISSUE THREAD

**Issue by roberts-ivanovs** [mibes404/zeep#5]
I would like to invoke the `zeep` crate programmatically to generate the code necessary (something similar to what https://crates.io/crates/savon does).

Note: I am not using `savon` already because their XML parser is subpar and does not work for my WSDL, whereas this crate works great.

**Comment by mibes404** [comment]
At the moment main.rs is a small wrapper around `FileWriter`. Would it help you if we put `FileWriter` in its own library, so you can call it directly from your code?

**Comment by roberts-ivanovs** [comment]
> At the moment main.rs is a small wrapper around `FileWriter`. Would it help you if we put `FileWriter` in its own library, so you can call it directly from your code?

I think it could be the first step in the right direction :+1:

**Comment by mibes404** [comment]
I've separated the XML/XSD logic in a separate `zeep-lib` library. Let me know if this construct works for you.

**Comment by roberts-ivanovs** [comment]
Yea, I think this might as well work. I will probably fork the repo and perform some changes (if I get the time) to suit my needs better. Thanks for this!
